theme: jekyll-theme-minimal  
title: Raveesh Garg  # Website title
logo: photo.jpg  # Adds profile photo in the sidebar
sidebar_link: false  # Removes GitHub profile link from the sidebar
show_downloads: false  # Hides "Download ZIP" and GitHub buttons
github: false
sidebar_links:
  "Experience": "#experience"
