remote_theme: fongandrew/hydeout
title: Raveesh Garg  
sidebar_link: true  
show_downloads: false  # Hides "Download ZIP" and GitHub buttons
github: false
description: Research Website
nav_links:
  - title: "Public CV"
    url: "Public_CV.pdf"
  - title: "Experience"
    url: "#experience"
  - title: "Education"
    url: "#education"
  - title: "Select Publications"
    url: "#publications"
  - title: "Awards and Honors"
    url: "#awards"
  - title: "Contact"
    url: "#contact"
