theme: jekyll-theme-minimal  
title: Raveesh Garg  # Website title
logo: photo.jpg  # Adds profile photo in the sidebar
sidebar_link: false  # Removes GitHub profile link from the sidebar
show_downloads: false  # Hides "Download ZIP" and GitHub buttons
github: false
description: >
  Research Website
  <a href="#education">Education</a> |
  <a href="#experience">Experience</a> |
  <a href="#publications">Publications</a> |
  <a href="#artifact">Artifacts, Workshops, Tutorials and Talks</a> |
  <a href="#contact">Contact</a>
